// Code generated by @open-rpc/generator DO NOT EDIT or ur gonna have a bad tiem
import { MethodMapping } from "@open-rpc/server-js/build/router";

import methods from "./methods";

export const methodMapping: MethodMapping = {
  create_user: methods.create_user,
  agent_websearch: methods.agent_websearch,
};

export default methodMapping;
